blog/urls.py
from django.urls import path
from . import views 

blog_patterns = ([
    #Paths del core
    path('', views.PostListView.as_view(), name='blogs'),
    #Path de las categorias
    path('<slug:slug>', views.PostDetailView, name='posts'),
    path('category/<int:category_id>/', views.CategoryListView.as_view(), name='category'), #El <category_id> es una cadena de caracteres y el int se utiliza para convertirlo a numero entero
], 'blog')

webplayground/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from pages.urls import pages_patterns
from profiles.urls import profiles_patterns
from blog.urls import blog_patterns
from messenger.urls import messenger_patterns
from about.urls import about_patterns
from portfolio.urls import portfolio_patterns
from services.urls import services_patterns
from contact.urls import contact_patterns

urlpatterns = [
        path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
        path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
        path('admin/', admin.site.urls),
        path('paginas/', include(pages_patterns)),
        path('', include('core.urls')),

        #Paths de auth
        # path('registro/', include(register_pattern)),
        path('cuentas/', include('django.contrib.auth.urls')),
        path('registro/', include('registration.urls')),

        path('equipo/', include(profiles_patterns)),

        #Paths de messenger
        path('messenger/', include(messenger_patterns)),

        #   Path para el blog
        path('blog/', include(blog_patterns)),

        #   Path para acerca de nosotros
        path('acerca-de-nosotros/', include(about_patterns)),

        #   Path para Portfolio
        path('portafolio/', include(portfolio_patterns)),

        #   Path para los servicios
        path('servicios/', include(services_patterns)),
    
        #   Path para la seccion de contactos
        path('contacto/', include(contact_patterns))
]

#Haciendo posible poder guardar imagenes localmente, es necesario tener el mode DEBUG en True en Settings.py
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
        

blog/models.py
from django.db import models
import uuid
from django.utils.timezone import now
from django.contrib.auth.models import User
from registration.models import Profile
from ckeditor.fields import RichTextField

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100,  verbose_name="Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Hora de actualizacion")

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
        ordering = [('created'), ]

    def __str__(self):
        return self.name

class Post(models.Model):
    uniqueId = str(uuid.uuid4())
    title = models.CharField(max_length=200, verbose_name="Titulo")
    content = RichTextField(verbose_name="Contenido")
    published = models.DateTimeField(verbose_name="Fecha de publicacion", default=now)
    image = models.ImageField(verbose_name="Imagen de portada", upload_to="blog", default="placeholder.png")
    
    author = models.ForeignKey(Profile, verbose_name="Autor", on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, verbose_name="Categorias", related_name="get_posts")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creacion")
    updated = models.DateTimeField(auto_now=True, verbose_name="Hora de actualizacion")

    slug = models.SlugField(unique=True, verbose_name="URL (sin espacios)", default=f"blog-{uniqueId}")
    blog_uuid = models.UUIDField(default=uniqueId, unique=True)

    class Meta:
        verbose_name = "Entrada"
        verbose_name_plural = "Entradas"
        ordering = ['-created']

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.content
    

blog/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'content')
        # widgets = {
        #     'name': forms.TextInput(attrs={'class': })
        # }

blog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.views.generic.detail import DetailView
from django.urls import reverse, reverse_lazy
from django.shortcuts import redirect

from .models import Post, Category
from .forms import CommentForm
from django.db.models import Count
from registration.models import Profile

class StaffRequieredMixin(object):

    #Este Mixin requerirar que el usuario se amiembro del staff
    #Evitando que usuarios no identificados, modifiquen la pagina desde las urls

    #El siguiente metodos(decorador) nos servira para pedir una autentificacion
    @method_decorator(staff_member_required)
    def dispatch(self, request, *args, **kwargs):
            #Verificando si es usuario es staff, y reedireccionandolo al panel de control, esto no es necesario si tenemos un decorador
            #if not request.user.is_staff:
                #return redirect(reverse_lazy('admin:login'))
            return super(StaffRequieredMixin, self).dispatch(request, *args, **kwargs)


class PostListView(ListView):
    model = Post
    ordering = ['-created']
    paginate_by = 5

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all() 
        
        return context
    

# class PostDetailView(DetailView):
#     model = Post
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context["categories"] = Category.objects.all() 
        
#         return context
def PostDetailView(request, slug):
    template_name = 'blog/post_detail.html'
    post = get_object_or_404(Post, slug=slug)
    all_post = Post.objects.all()
    categories = Category.objects.all()
    profiles = Profile.objects.all()
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    return render(request, template_name, {'post': post,
                                            'post_list': all_post,
                                            'comments': comments,
                                            'categories': categories,
                                            'new_comment': new_comment,
                                            'comment_form': comment_form,
                                            "profiles": profiles})

class CategoryListView(ListView):
    queryset = Category.objects.all()
    context_object_name = 'categories_list'
    template_name = "blog/category.html"

    def get_queryset(self):
        return Category.objects.filter(id=self.kwargs.get('category_id')).all()
    


def blog(request):
    posts = Post.objects.all()
    return render(request,'blog/blog.html', {'posts':posts})

def category(request, category_id):
    category = get_object_or_404(Category, id=category_id) #forzando un error por si no se encuentra el id
    return render(request,'blog/category.html', {'category':category})

blog/templates/blog/blog.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
{% for post in posts %}
  <section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-innerv text-center rounded">
            <h2 class="section-heading mb-5">
              <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span> <!-- Cambiando el formato de la fecha -->
              <span class="section-heading-lower">{{post.title}}</span>
            </h2>
            <p class="mb-0">
              <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt=""> 
            </p>
            <p class="mb-0 mbt">
             {{post.content|linebreaks}} <!-- Haciendo visibles los saltos de linea desabilitados por defecto-->
            </p>
              <p><a href="{% url 'blog:post' post.title|slugify %}"></a></p>
              <span class="section-heading-under">Publicado por <em><b>{{post.author}}</b></em> en <em>
              <!-- <a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em></span> -->
              <em>
              {% for category in post.categories.all %}  <!-- Sin el all no muestra las categorias -->
                <a href="{% url 'category' category.id %}" class="link">{{category.name}}</a>{% if not forloop.last %}, {% endif %} <!-- Comprueba si el for esta en el ultimo valor -->
              {% endfor %}
              </em>
              </span>
          </div>

        </div>
      </div>
    </div>
  </section>
{% endfor %}
{% endblock %}


    

blog/templates/blog/category.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Categorias{% endblock %}

{% block content %}
{% comment %} <section class="page-section cta">
  
  <div class="container">
    <div class="row">
      <div class="col-xl-9 mx-auto">
        <div class="cta-innerv text-center rounded">
          <h2 class="section-heading mb-5">
            <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span> <!-- Cambiando el formato de la fecha -->
                  <span class="section-heading-lower">{{post.title}}</span>
                </h2>
                <p class="mb-0">
                  <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt=""> 
                </p>
                <p class="mb-0 mbt">
                {{post.content|linebreaks}} <!-- Haciendo visibles los saltos de linea desabilitados por defecto-->
                </p>
                <p class="mb-0 mbt">
                  <span class="section-heading-under">Publicado por <em><b>{{post.author}}</b></em> en <em>
                    <!-- <a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em></span> -->
                  <em>
                    {% for category in post.categories.all %}  <!-- Sin el all no muestra las categorias -->
                    <a href="{% url 'blog:category' category.id %}" class="link">{{category.name}}</a>{% if not forloop.last %}, {% endif %} <!-- Comprueba si el for esta en el ultimo valor -->
                    {% endfor %}
                  </em>
                </span>
                </p>
              </div>
              
            </div>
          </div>
        </div>
      </section> {% endcomment %}
      
      <main id="main">
        
        <!-- ======= Blog Section ======= -->
        <section id="blog" class="blog">
          <div class="container" data-aos="fade-up">
            
            <div class="row">
              
              <div class="col-lg-8 entries">
                
                {% for category_object in categories_list %} <!-- Busca todas las instancias de 1 -->
                 {% for post in category_object.get_posts.all %}
                <article class="entry">
                  
                  <div class="entry-img">
                    <img src="{{ post.image.url }}" alt="" class="img-fluid">
                  </div>
                  
                  <h2 class="entry-title">
                    <a href="{% url 'blog:posts' post.slug %}">{{ post.title }}</a>
                  </h2>
                  
                  <div class="entry-meta">
                    <ul>
                      <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ post.author }}</a></li>
                      <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{ post.published}}</time></a></li>
                    </ul>
                  </div>
      
                  <div class="entry-content">
                      {{ post.content|truncatechars_html:355|safe }}
                    <div class="read-more">
                      <a href="{% url 'blog:posts' post.slug %}">Leer Mas</a>
                    </div>
                  </div>
      
                </article><!-- End blog entry -->
                {% endfor %}
              {% endfor %} 
      
              </div><!-- End blog entries list -->
      
              {% include 'blog/category_list.html' %}
      
            </div>
      
          </div>
        </section><!-- End Blog Section -->
      
      </main><!-- End #main -->


{% endblock %}


    

blog/templates/blog/category_list.html

<div class="col-lg-4">

    
<div class="sidebar">

    <div class="search-form">
    <form action="" class="searsh-form">
        <input type="text" required class="search">
        <button type="submit" class="button-no-bg"><i class="bi bi-search"></i></button>
    </form>
    </div><!-- End sidebar search formn-->

    <h3 class="sidebar-title">Categorias</h3>
    <div class="sidebar-item categories">
    <ul>
    {% for category in categories.all %} <!-- Busca todas las instancias de 1 -->
        <li><a href="{% url 'blog:category' category.id %}">{{category}}</a></li>
    {%endfor%}

    </ul>
    </div><!-- End sidebar categories-->
        <h3 class="sidebar-title">Públicaciones Recientes</h3>
        {% for post in post_list|slice:":5" %}
        <div class="sidebar-item recent-posts">
            <div class="post-item clearfix">
                <img src="{{post.image.url}}" alt="">
                <h4><a href="{% url 'blog:posts' post.slug %}">{{post.title}}</a></h4>
                <time datetime="2020-01-01">{{post.published}}</time>
            </div>
        </div>
        {% endfor %}
    </div><!-- End sidebar recent posts-->

</div><!-- End sidebar -->

</div><!-- End blog sidebar -->

blog/templates/blog/post_confirm_delete.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}Borrar página{% endblock %}
{% block content %}
{% include 'pages/includes/pages_menu.html'%}
<main role="main">
  <div class="container">
    <div class="row mt-3">
      <div class="col-md-9 mx-auto">
        <div>
            <form action="" method="post">{% csrf_token %}
                <p>¿Estás seguro de que quieres borrar "<b>{{ object }}</b>"?</p>
                  <input type="submit" class="btn btn-primary btn-block" value="Si, borrar pagina" />
            </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}{{post.title}}{% endblock %}
{% block content %}

{% if request.user.is_staff %}
  {% comment %} <p><a href="{% url 'blog:update' page.id %}">Editar</a></p> {% endcomment %}
{% endif %}
   <section id="blog" class="blog mt-5">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry entry-single">

              <div class="entry-img">
                <img src="{{ post.image.url }}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="#">{{ post.title }}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ post.author }}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{ post.published }}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="blog-single.html">{{comments.count}} Comentario/s</a></li>
                </ul>
              </div>

              <div class="entry-content">
                {{ post.content|safe }}
              </div>

              <div class="entry-footer">
                <i class="bi bi-folder"></i>
                <ul class="cats">
                  {% for category in categories.all %} <!-- Busca todas las instancias de 1 -->
                    <li><a href="{% url 'blog:category' category.id %}">{{category}}</a></li>
                  {% endfor %}
                </ul>

                <i class="bi bi-tags"></i>
                <ul class="tags">
                  <li><a href="#">Creative</a></li>
                  <li><a href="#">Tips</a></li>
                  <li><a href="#">Marketing</a></li>
                </ul>
              </div>

            </article><!-- End blog entry -->

            <div class="blog-author d-flex align-items-center">
              {% if not post.author.avatar.url %}
                <img src="{% static 'core/img/no-avatar.png' %}" class="rounded-circle float-left" alt="">
              {% else %}
                <img src="{{ post.author.avatar.url }}" class="rounded-circle float-left" alt="">
              {% endif %}
              <div>
                {% if post.author.user.get_full_name|length > 1 %}
                  <h4>{{post.author.user.get_full_name}}</h4>
                {% else %}
                  <h4>Escritor de Codey</h4>
                {% endif %}
                <div class="social-links">
                  {% if post.author.facebook_url %}
                    <a href="{{post.author.facebook_url}}" target="_blank"><i class="bi bi-facebook"></i></a>
                  {% endif %}
                  {% if post.author.twitter_url %} 
                    <a href="{{post.author.twitter_url}}" target="_blank"><i class="bi bi-twitter"></i></a> 
                  {% endif %}
                  {% if post.author.instagram_url %} 
                    <a href="{{post.author.instagram_url}}" target="_blank"><i class="biu bi-instagram"></i></a>
                  {% endif %}
                  {% if post.author.tiktok_url %} 
                    <a href="{{post.author.tiktok_url}}" target="_blank"><i class="biu bi-tiktok"></i></a>
                  {% endif %}
                </div>
                <p>
                  {% if post.author.bio %}
                    {{post.author.bio}}
                  {% else %}
                    Soy un escritor y moderador de esta magnifica pagina web, siguenos en todas nuestras redes sociales para no perderte de ninguna novedad!
                  {% endif %}
                </p>
              </div>
            </div><!-- End blog author bio -->

            <div class="blog-comments">
              <h4 class="comments-count">{{comments.count}} Comentario/s</h4>

              {% for comment in comments %}
                <div id="comment-1" class="comment">
                  <div class="d-flex">
                    <div class="comment-img"><img src="{% static 'core/img/no-avatar.png' %}" alt=""></div>
                    <div>
                      <h5><a href="#" class="text-info">{{comment.name}}</a> <a href="#" class="reply"><i class="bi bi-reply-fill"></i> Reply</a></h5>
                      <time datetime="2020-01-01">{{comment.created}}</time>
                      <p>
                        {{ comment.content | linebreaks }}
                      </p>
                    </div>
                  </div>
                </div><!-- End comment #1 -->
              {% endfor %}

              {% comment %} <div id="comment-2" class="comment">
                <div class="d-flex">
                  <div class="comment-img"><img src="assets/img/blog/comments-2.jpg" alt=""></div>
                  <div>
                    <h5><a href="">Aron Alvarado</a> <a href="#" class="reply"><i class="bi bi-reply-fill"></i> Reply</a></h5>
                    <time datetime="2020-01-01">01 Jan, 2020</time>
                    <p>
                      Ipsam tempora sequi voluptatem quis sapiente non. Autem itaque eveniet saepe. Officiis illo ut beatae.
                    </p>
                  </div>
                </div>

                <div id="comment-reply-1" class="comment comment-reply">
                  <div class="d-flex">
                    <div class="comment-img"><img src="assets/img/blog/comments-3.jpg" alt=""></div>
                    <div>
                      <h5><a href="">Lynda Small</a> <a href="#" class="reply"><i class="bi bi-reply-fill"></i> Reply</a></h5>
                      <time datetime="2020-01-01">01 Jan, 2020</time>
                      <p>
                        Enim ipsa eum fugiat fuga repellat. Commodi quo quo dicta. Est ullam aspernatur ut vitae quia mollitia id non. Qui ad quas nostrum rerum sed necessitatibus aut est. Eum officiis sed repellat maxime vero nisi natus. Amet nesciunt nesciunt qui illum omnis est et dolor recusandae.

                        Recusandae sit ad aut impedit et. Ipsa labore dolor impedit et natus in porro aut. Magnam qui cum. Illo similique occaecati nihil modi eligendi. Pariatur distinctio labore omnis incidunt et illum. Expedita et dignissimos distinctio laborum minima fugiat.

                        Libero corporis qui. Nam illo odio beatae enim ducimus. Harum reiciendis error dolorum non autem quisquam vero rerum neque.
                      </p>
                    </div>
                  </div>

                  <div id="comment-reply-2" class="comment comment-reply">
                    <div class="d-flex">
                      <div class="comment-img"><img src="assets/img/blog/comments-4.jpg" alt=""></div>
                      <div>
                        <h5><a href="">Sianna Ramsay</a> <a href="#" class="reply"><i class="bi bi-reply-fill"></i> Reply</a></h5>
                        <time datetime="2020-01-01">01 Jan, 2020</time>
                        <p>
                          Et dignissimos impedit nulla et quo distinctio ex nemo. Omnis quia dolores cupiditate et. Ut unde qui eligendi sapiente omnis ullam. Placeat porro est commodi est officiis voluptas repellat quisquam possimus. Perferendis id consectetur necessitatibus.
                        </p>
                      </div>
                    </div>

                  </div><!-- End comment reply #2-->

                </div><!-- End comment reply #1-->

              </div><!-- End comment #2--> {% endcomment %}

              <div class="reply-form">
                {% if new_comment %}
                  <div class="alert alert-success" role="alert">
                    Tu comentario se ha enviado!, <strong>esta en proceso de verificacion...</strong>
                  </div>
                {% else %}
                  <h4>Deja un comentario 😎</h4>
                  <p>Protegemos tu direccion de correo, no sera publico. Campos obligatorios marcados con * </p>
                  <form method="post">
                    {{ comment_form|crispy }} 
                    {% csrf_token %}
                  <button type="submit" class="btn btn-primary">Enviar Comentario</button>
                  
                </form>
                {% endif %}
                
              </div>

            </div><!-- End blog comments -->

          </div><!-- End blog entries list -->

          {% include 'blog/category_list.html' %}


        </div>

      </div>
    </section><!-- End Blog Single Section -->
{% endblock %}


blog/templates/blog/post_list.html
{% extends 'core/base.html' %}

{% load static %}

{% block title %}Blog{% endblock %}

{% block content %}
  <main id="main">
    
    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">
        
        <div class="row">
          
          <div class="col-lg-8 entries">
          
            {% for post in post_list %} <!-- Busca todas las instancias de 1 -->
            <article class="entry">
              
              <div class="entry-img">
                <img src="{{ post.image.url }}" alt="" class="img-fluid">
              </div>
              
              <h2 class="entry-title">
                <a href="{% url 'blog:posts' post.slug %}">{{ post.title }}</a>
              </h2>
              
              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="blog-single.html">{{ post.author }}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="blog-single.html"><time datetime="2020-01-01">{{ post.published}}</time></a></li>
                </ul>
              </div>

              <div class="entry-content">
                  {{ post.content|truncatechars_html:355|safe }}
                <div class="read-more">
                  <a href="{% url 'blog:posts' post.slug %}">Leer Mas</a>
                </div>
              </div>

            </article><!-- End blog entry -->
            {% endfor %}

            {% if is_paginated %}
              <div class="blog-pagination">
                <ul class="justify-content-center">
                  {% if page_obj.has_previous %}
                    <li>
                      <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                    </li>
                  {% else %}
                    <li class="disabled">
                      <a href="#" tabindex="-1">&laquo;</a>
                    </li>
                  {% endif %}
                  {% for i in paginator.page_range %}
                    <li class="{% if page_obj.number == i %}active{% endif %}">
                      <a href="?page={{i}}">{{i}}</a>
                    </li>
                  {% endfor %}
                  {% if page_obj.has_next %}
                  <li>
                      <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>

                  {% else %}
                    <li class="disabled">
                      <a href="#" tabindex="-1">&raquo;</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            {% endif %}

          </div><!-- End blog entries list -->

          {% include 'blog/category_list.html' %}

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

{% endblock %}